import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { getPages } from "../../../sanity/sanity-utils";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex items-center gap-4 p-4 max-w-6xl mx-auto">
          <Link href="/">nu-zanimo</Link>
          <ul className="flex gap-4">
            {pages.map((page) => (
              <li key={page._id}>
                <Link className="px-4 py-2" href={`/${page.slug}`}>
                  {page.title}
                </Link>
              </li>
            ))}
          </ul>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
